#spring:
#  data:
#    mongodb:
#      username: anish
#      password: anish123
#      host: mongo
#      port: 27017
#      database: customer
#      authentication-database: admin
spring:
  data:
    mongodb:
      uri:
      auto-index-creation: true

server:
  port: 8090